// GENERATED FILE — do not edit by hand.
// Regenerated by scripts/generate-image-manifest.mjs on every build.
// To add a photo: drop it in /public/images/<slot>.jpg and rebuild.

export const imageManifest: Record<string, string> = {
  "hero-fallback-loaf": "/images/hero-fallback-loaf.jpg",
  "menu-banana-nut-muffins": "/images/menu-banana-nut-muffins.jpg",
  "menu-jalapeno-queso-loaf": "/images/menu-jalapeno-queso-loaf.jpg",
  "menu-oatmeal-raisin-cookies": "/images/menu-oatmeal-raisin-cookies.jpg"
};
